---
name: CI
on:
  push:
    paths: [yae.json, '**/*.nix', '*.lock']
  pull_request:
    paths: [yae.json, '**/*.nix', '*.lock']
  workflow_dispatch:
  workflow_run:
    workflows: [Yae Update]
    types: [completed]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        if: github.ref == 'refs/heads/main'
        with:
          name: tsutsumi
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true
      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"
      - run: om ci
